labels:
  # -- L of LPSD of Gotrade Service Tree
  landscape: develop
  # -- P of LPSD of Gotrade Service Tree
  platform: system
  # -- P of LPSD of Gotrade Service Tree
  service: template
  # -- Infrastructure layer this application belongs to
  layer: "1"
  # -- Team in charge of this chart
  team: ESD
  # -- chart version
  version: 1.4.0
